

POST http://localhost:5005/api/DC_CRAC_ HTTP/1.1
Content-Type: application/x-www-form-urlencoded

{
    "name": "sample",
    "time": "huhu"
}



###

GET http://localhost:5002/api/location/?id=2$group=tmone

###

POST http://localhost:5004/login
Content-Type: application/json

{
    "username" : "hasanul"
}
